/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8674e082-6b2f-4c71-9e77-f9a5448b5048",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_liQm3MZn6",
    "aws_user_pools_web_client_id": "4dlt4knmvkkebhm7nsas6tgml4",
    "oauth": {},
    "aws_mobile_analytics_app_id": "5eabec8de3e84b66b6a10b791349bb1a",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "awsamplifyecommerce-items-practice",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "awsamplifyecommerceapi",
            "endpoint": "https://0vmzyi3ned.execute-api.us-east-1.amazonaws.com/practice",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "awsamplifyecommerce-20200829175038-hostingbucket-practice",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://awsamplifyecommerce-20200829175038-hostingbucket-practice.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
